# Generated by Django 5.1.2 on 2024-12-07 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.AlterField(
            model_name='user',
            name='current_active_role',
            field=models.ForeignKey(blank=True, help_text='The currently active role for this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_current_role', to='tutorials.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='tutorials.role'),
        ),
    ]
