# Generated by Django 5.1.2 on 2024-11-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("tutor", "Tutor"),
                    ("admin", "Admin"),
                ],
                default="student",
                max_length=10,
            ),
        ),
    ]
