# Generated by Django 5.1.2 on 2024-11-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_programminglanguage_subject_lesson'),
        ('tutorials', '0002_user_role'),
    ]

    operations = [
    ]
