# Generated by Django 5.1.2 on 2024-12-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_role_remove_user_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', to='tutorials.role'),
        ),
    ]
