# Generated by Django 5.1.2 on 2024-11-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('tutor', 'Tutor')], default='student', max_length=10, verbose_name='User Type'),
        ),
    ]
