# Generated by Django 5.1.2 on 2024-11-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
