# Generated by Django 5.1.2 on 2024-11-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_lessonrequest_delete_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('allocated', 'Allocated')], default='pending', max_length=10),
        ),
    ]
