# Generated by Django 5.1.2 on 2024-12-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0005_tutoravailability"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutoravailability",
            name="end_recurrence_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tutoravailability",
            name="recurrence",
            field=models.CharField(
                choices=[
                    ("none", "One-time"),
                    ("weekly", "Weekly"),
                    ("biweekly", "Bi-weekly"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
