# Generated by Django 5.1.2 on 2024-11-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_lessonrequest_status'),
        ('tutorials', '0005_tutoravailability'),
    ]

    operations = [
    ]
