# Generated by Django 5.1.2 on 2024-12-03 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0006_merge_20241130_1429"),
        ("tutorials", "0006_tutoravailability_end_recurrence_date_and_more"),
    ]

    operations = []
